### PR TITLE
Correct scripts.lib::dump documentation

### PR DESCRIPTION
**Pull request by Fayti1703**
### Problem

The documentation for `scripts.lib`'s `dump` function is incorrect and misleading.

### CODE REVIEW

**Comment by Fayti1703** [comment]
I have read the CLA Document and I hereby sign the CLA

---

We might need to set up some exclusions for ComCODE volunteers for this...

**Comment by seanmakesgames** [comment]
> I have read the CLA Document and I hereby sign the CLA
> 
> We might need to set up some exclusions for ComCODE volunteers for this...

Needs to be exact I think. And I'm trying to figure out the right path for this. Managing the 'allowlist' per-repo-per-volunteer add is a lot of overhead

**Comment by Fayti1703** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Fayti1703** [comment]
recheck

**Comment by seanmakesgames** [comment]
Correct_scripts_lib__dump_documentation_by_Fayti1703_·_Pull_Request__384_·_comcode-org_hackmud_wiki
This is what happens when you use your own PAT for the bot. :P

**Review by seanmakesgames — APPROVED** [review]

**Comment by Fayti1703** [comment]
By the way, do we want auto-locking on merge/close? I personally don't really see the use, and it prevents post-merge discussion on a PR.

**Comment by seanmakesgames** [comment]
>By the way, do we want auto-locking on merge/close? I personally don't really see the use, and it prevents post-merge discussion on a PR.

people can erase their acceptance of the CLA--

I believe it only locks the thread in which a CLA was signed. --and only for non-collaborators

**Pull request merged**
