### PR TITLE
Rename 'Preprocessor Directives' -> 'JavaScript Extensions'

### LINKED ISSUE #426: 'Preprocessor Directives' section name is inaccurate
### Problem

The 'Preprocessor Directives' section's name doesn't accurately reflect its contents; it currently contains 5 global variables in addition to its 4 preprocessor directives.

### Context

Possible new name: "JavaScript Extensions" (this name would also be generic enough to include things like the `JSON.stringify`/`JSON.parse` overrides)

### PR DESCRIPTION
**Pull request by Fayti1703**
### Problem

Fixes #426 

### Problems with this change

~~This PR is currently marked as a draft because old direct links to pages under the renamed section fail with this PR applied.
There are ways to set up redirects in Docusaurus, chiefly [@docusaurus/plugin-client-redirects/](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-client-redirects/); but that would be a significant dependency addition and I'm not sure how we want to handle that.~~

Currently considered "not an issue" (see discussion).

### CODE REVIEW

**Comment by seanmakesgames** [comment]
Do we think there are many direct links to these pages? Can we just break them and not worry about it?

**Comment by Fayti1703** [comment]
There's a couple recent ones on Discord from @matr1x-hackmud; other those I doubt it.

**Comment by Fayti1703** [comment]
Also is it just me or is the worker for the security/license issues check _extremely_ slow for no apparent reason? It's been stuck trying to check out the repo for _20 minutes_ now (without even getting to the actual checkout!)

**Comment by seanmakesgames** [comment]
> There's a couple recent ones on Discord from @matr1x-hackmud; other those I doubt it.

I wouldn't worry about it then. @matr1x-hackmud can update his links if it matters, but people will find stuff even if links are broken.

**Comment by Fayti1703** [comment]
> I wouldn't worry about it then.

Alright, marking as ready for review.

**Review by mogery — APPROVED** [review]
LGTM!

**Pull request merged**
