### PR TITLE
Draft Upgrade Policy & Process

### LINKED ISSUE #35: Dependency Upgrade Policy
### Problem

We do not have a policy for upgrading the dependencies we rely upon.

### Goal

Our goal is to develop a policy that answers:

- How do we propose and assess the need for a dependency upgrade?
- How do we implement and review a dependency upgrade?

### Tasks

- [x] Decide where this policy will be documented.
- [x] Document an assessment procedure:
  - [x] Decide where upgrade assessments should be documented (e.g. PR, issue, project)
  - [x] Identify required information for an upgrade decision
  - [x] Define (or rule out) a measure for perceived importance and/or complexity
- [x] Document a review procedure:
  - [x] Identify required information for implementation and review
  - [x] ~~Define a test plan~~ really just standard review procedure, any strict definition can be done with workflow impl

Several items are out of scope for this issue, but have been acknowledged as potential future work:

- Upgrade workflows and automation
- Regular auditing of dependencies
- Addressing implications of deferring/denying upgrades (e.g. security)

### PR DESCRIPTION
**Pull request by seanmakesgames**
Fixes #35

### CODE REVIEW

**Comment by danswann** [comment]
1. If this is supposed to be a policy global to our projects, does it belong in the wiki repo?
2. If we're already optimistically upgrading minor versions, why do we need to do that again as a prerequisite for a major version upgrade? Seems like in the overwhelming majority of cases, steps 1-9 would be unnecessary. Is that what the  "only do the steps which are applicable" clause is supposed to solve?
3. Should we consider configuring dependabot to automatically open package bump PRs?

**Comment by danswann** [comment]
Makes sense.

**Review by danswann — APPROVED** [review]

**Comment by tukib** [comment]
Looks great, though I think the policy & process could be clearer to answer these questions:
- At what point in the upgrade process is an issue created for documenting upgrade-specific decisions?
- Does the policy support upgrading across major versions optimistically as long as they are considered stable?

**Review by tukib — APPROVED** [review]
Looks good to me!

**Pull request merged**
