### PR TITLE
Add Chat API docs

### PR DESCRIPTION
**Pull request by mogery**
### Problem
This is a port of [my old documentation from the forums](https://hackmud.com/forums/general_discussion/chat_api_documentation). We should likely have an official description for this API.

### CODE REVIEW

**Comment by seanmakesgames** [comment]
Usage of existing ComCODE IP approved. Thank you for posting the source and link.

**Comment by danswann** [comment]
Dunno whether it's worth blocking this to make it more "complete," but FWIW I think `chat_history` works fine now? I seem to be able to get ranges in which I've neither joined nor left.

**Comment by mogery** [comment]
> Dunno whether it's worth blocking this to make it more "complete," but FWIW I think `chat_history` works fine now? I seem to be able to get ranges in which I've neither joined nor left.

Oh, really? Awesome! Worth blocking for that IMO

**Review by matr1x-hackmud — APPROVED** [review]
LGTM; enough endpoints are in here for a doc v1

**Pull request merged**
